{% set name = "ctdcal" %}
{% set version = "0.1.5b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ctdcal-{{ version }}.tar.gz
  sha256: 506acef1c453c459e1c3209fd637d5374a54e91ac800a4d26295d7daeae3ede8

build:
  number: 0
  noarch: python
  entry_points:
    - ctdcal=ctdcal.__main__:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - click ==8.0.1
    - cmocean ==2.0
    - gsw ==3.4.0
    - matplotlib-base ==3.4.3
    - numpy ==1.21.2
    - pandas ==1.3.3
    - python >=3.8
    - pyyaml ==5.4.1
    - scipy ==1.7.0

test:
  imports:
    - ctdcal
    - ctdcal.scripts
  commands:
    - pip check
    - ctdcal --help
  requires:
    - pip

about:
  home: https://github.com/cchdo/ctdcal
  summary: CTD and bottle data processing package from UCSD ODF
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - asmith75218
    - jojobozz
